### ISSUE TITLE
lik as score type

### ISSUE THREAD

**Issue by matthewtuby** [cran/HCR#1]
What do you mean by lik? Could you resolve this abbreviation?

https://github.com/cran/HCR/blob/827a42d1c3dd91f1b7844cb580a0d6221c7e85ad/R/utility_functions.R#L213

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the DESCRIPTION file for the package authors.

**Comment by matthewtuby** [comment]
Thanks! Although it's likelihood.
